### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by atd-schubert** [mapbender/mapbender#1064]
**Is your feature request related to a problem? Please describe.**
I try to use Mapbender with latest PHP 7.3, but it cause errors.

**Describe the solution you'd like**
Compatibility to PHP >= 7.3

**Describe alternatives you've considered**
Using PHP 7.2

**Additional context**

**Comment by atd-schubert** [comment]
For example when running `console assert:install`

Results in the following error:

```
 mapbender-console assets:install

                                                                                                    
  [Symfony\Component\Debug\Exception\ContextErrorException]                                         
  Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  

```

**Comment by binarious** [comment]
@werrolf We're also getting this error. This was an [issue in doctrine](https://github.com/doctrine/orm/issues/7402) which is also called while installing assets. This has been fixed in doctrine/orm v2.6, but it isn't compatible with Symfony 2.8. Is there any progress in upgrading Mapbender to Symfony 3 or 4? Symfony 2.8 ends its support in November 2019.

**Comment by binarious** [comment]
@astroidex Can you comment on this issue and the Symfony compatibility of mapbender?

**Comment by LazerTiberius** [comment]
Currently Mapbender is not compatible with Php 7.3 , but we are working on it.

**Comment by binarious** [comment]
@LazerTiberius Thanks for the answer. Could you also comment on the Symfony support? Wouldn't it be better to leave this issue opened until it's resolved?
