### ISSUE TITLE
[frontend] [Legend] - group title is shown in legend although it is disabled

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1127]
**Describe the bug**
Legend - group title is shown in legend although it is disabled.

**To Reproduce**
1. Go to administration to your application to the legend element and disable all titles - via checkbox (wms, group, layer)
2. Go to your application
3. Load service (has groups) https://rio.obk.de/cgi-bin/mapserv?map=/home1/data/umn/obk/obk_amt68_freizeitinformationen.map&REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.3.0
4. See error: Group title is displayed in the legend output

see demo for this ticket: https://demo.mapbender.org/nightly/application/test_ticket_1127

**Expected behavior**
do not show group title

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8beta
 - Database:  -
 - Browser chrome, firefox

**Screenshots / Logmessage**

settings in admin backend: for legend element
![mb_legend_no_group_layer_admin](https://user-images.githubusercontent.com/996298/54818296-2ff7ff80-4c99-11e9-9487-65bb7530fd61.png)

Behaviour in Application
![mb_group_layer_no_display_map](https://user-images.githubusercontent.com/996298/54818332-4bfba100-4c99-11e9-8465-86ac54c4ccda.png)

**Comment by werrolf** [comment]
Confirmed.  
The "translation" of the good old typo option name `showGrouppedTitle` (sic; that's the actual name of the backend input field since 5cfc177128d6bd0f9e81c1494b12549481eb9c60) to was lost in 9155ea7173628a18b8af4b80ab5e09033432073c.

Be advised that the option name `showGroupedLayerTitle` as seen even in current YAML application definitions doesn't do anything, and hasn't done anything since the same commit 5cfc177128d6bd0f9e81c1494b12549481eb9c60 circa spring 2013.

A fix should solve both issues: make backend + YAML application options apply even if they use historic misspellings.
