### ISSUE TITLE
[frontend][PrintClient] print with rotation sometimes does not print the selected area

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1129]
**Describe the bug**
When you want to print and choose rotation and you change the print template (f.e. from A4 portrait to A4 landscape) the the result in the pdf is not the one that was selected in the map

**To Reproduce**
1. Go to https://demo.mapbender.org/nightly/application/mapbender_user
2. Open Print dialog and rotate the map with -45
3. Create the pdf and compare the output with the area selected
4. Change the print template to A4 landscape and print again and compare the output with the map

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8 beta 3
 - Browser [

**Screenshots / Logmessage**

![mbp2](https://user-images.githubusercontent.com/996298/54839137-8a5d8400-4cca-11e9-9097-ce83480da74c.png)
![mb_p1](https://user-images.githubusercontent.com/996298/54839150-8f223800-4cca-11e9-9625-96b40a7d543a.png)

**Comment by werrolf** [comment]
It's been identified and fixed independently.
The "sometimes" is explained by the dragging motion no longer being applied after fixing the "Firefox problem" with the new rotation handling -- which wasn't really a Firefox problem I might add, Firefox just tends to be stricter about undeclared JavaScript variables, which is a good thing.

In short, if you didn't drag the print selection, you've never seen this issue. That's how it slipped.

This was fixed in [3ec4bea](https://github.com/mapbender/mapbender/commit/3ec4bea6456e1cc5e4342f598abfb853528897c0). Rectangle drag has the intended, intuitive effect again. Fix is already on the current release/3.0.7 branch (yeah I know).

Please reconfirm.

**Comment by astroidex** [comment]
I tested with v3.0.8-beta4
Works fine

I close the ticket
