### ISSUE TITLE
[frontend][WMC Loader] with thematic layertree (show layerset-title) title disappears after load

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1132]
**Describe the bug**
Create an application with WMC and layertree with show thematic layer (i.e. show layertree-names)

**To Reproduce**
1. Create an application with WMC and layertree with show thematic layer (i.e. show layerset-names) you can use https://demo.mapbender.org/nightly/application/test_wmc
2. save a wmc and set it to public
3. load the wmc 
4. See error: the layerset-title is gone

**Expected behavior**
Layerset
**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8beta and before

**Screenshots / Logmessage**

**Additional context**

**Comment by werrolf** [comment]
Correction: the Layerset is gone from the LayerTree, not just the title.

No Mapbender 3 version ever saved Layerset information from its `getMapState` method (which is used by Wmc and other things). A loaded Wmc could never land into any "thematic" layerset display because it held no information about which one would be the right one.

The Layerset disappears from the LayerTree because Wmc loading removes sources, most commonly just all sources (but there are configuration knobs for that), which may produce an entirely empty Layerset, which is visually removed from the LayerTree to avoid collateral errors.

I suppose you want to CR for including Layerset information into the dumped Wmc state and have it reloaded.

**Comment by eschuettler** [comment]
Thank you!
We always try to improve Mapbender.

Feature wishes can also be ordered at WhereGroup.
WhereGroup GmbH & Co. KG
info@wheregroup.com
https://wheregroup.com/kontakt.html
