### ISSUE TITLE
[PrintClient] FeaturePrint does not work anymore from featureInfo-result-Link

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1136]
**Describe the bug**
Mapbender print offered feature-data print that you can trigger via digitizer or feature info. 
With 3.0.8.3beta3 the print does not work anymore.

Description about how to configure the featuredata-print:
https://github.com/mapbender/mapbender-documentation/pull/55/files

Error message for 3.0.8beta3
```
Unsupported mbPrintClient.printDigitizerFeature invocation. Must pass in printable attributes object (preferred) or OpenLayers feature to extract them from. Update your mapbender/digitizer to >=1.1.68 
Arguments { 0: "feature_demo", 1: 184, … }
js:29939:17

Error: Unsupported mbPrintClient.printDigitizerFeature invocation. Must pass in printable attributes object (preferred) or OpenLayers feature to extract them from. Update your mapbender/digitizer to >=1.1.68
```

**To Reproduce**
1. You need a WMS that supports featuredata-print
2. get a featureinfo from your WMS
3. start the featureprint for the feature
4. Error message occurs

**Expected behavior**
Print client should open and a print output should be possible

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8beta (worked fine with 3.0.7.7)

**Screenshots / Logmessage**

**Additional context**

**Comment by werrolf** [comment]
This is as intended and the error message explains exactly what to do. You're using an undocumented, unfinished feature that had severe design problems from the start. For one, the assumption that there is a global declaration for your `feature_demo` type on a global `featureType` service. That service isn't even defined in Mapbender proper. Every Digitizer in every application can completely redefine its feature types. The old `printDigitizerFeature` logic was replaced because it was incapable of printing Digitizer features in many real-world circumstances.

Digitizer was made compatible with this change. Your hacked featureinfo response can be made compatible with this by injecting the attributes that you want printed. In any scope where you're capable of generating a feature info response, all attributes should be as trivially available as the `[gid]` in [your documentation](https://github.com/mapbender/mapbender-documentation/blob/77c5780415e07e393c3b173d9c4c5be751d520f2/en/bundles/Mapbender/CoreBundle/elements/printclient.rst#3-call-feature-print-from-featureinfo).
