### ISSUE TITLE
limited view in element-configuration

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#1209]
**Describe the bug**
In older versions you could see the selectbox at the end of the element-configuration. In newer versions this dialog is cut to all open fields when you open it - not maximized to full height of screen. Related to the browser ans system you use this view is very confusing if you don't know, that you can scroll down after the select in the selectbox: 

**To Reproduce**
1. Go to an application
2. Add the navigationtoolbar element
3. change the anchor point
4. See the confusing behaviour (you need to scroll down to see the rest of the box)

**Expected behavior**
You can see every option of the dialog without the need to scrolll down - like before. 

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.4
 - Database: PSQL 10
 - Browser chrome, firefox

**Screenshots / Logmessage**

![Auswahl_053](https://user-images.githubusercontent.com/13517141/65668034-44022c80-e041-11e9-80f9-c8a7ac2d0919.png)

**Comment by rschwammborn** [comment]
Hello @CharlyUnicorn ,
thanks for sharing this slightly confusing backend behaviour.
Indeed, this seems to be tricky...at least the appearing scroll bar on the right gives a little bit of visual support as soon as the anchor point is adjusted, so there's that. Because the alternative workflow is nevertheless sound, don't expect a "fix" in 3.0.8.x. Instead, keep on looking forward to Mapbender 3.1, which will include a redesign of the backend window behaviour!
