### ISSUE TITLE
[Frontend] [featureinfo] new featureinfo-highlight on map is still there when the fi-dialog is closed

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1325]
**Describe the bug**
FeatureInfo-Highlight provides highlight for the polygon geometry that comes as WKT via feature Info (will come in Mapbender in 3.2.3).
When you close a fi-dialog the highlighted feature is still on the map and does not disappear. (This behaviour is in combination with deactivateonclose-> false for featureinfo)

**To Reproduce**
1. Activate featureinfo with Highlight=true and  deactivateonclose-> false
2. add a WMS that supports featureinfohighlight f.e  http://mb31.wheregroup.lan/application/mapbender_user_featureinfo_highlight
3. Activate featurinfo and see the highlighted areas in the map
4. close the dialog (featureinfo-element is not deactivated as of setting deactivateonclose-> false)
5. See error: areas are still highlighted in the map

**Expected behavior**
When you close the fi-dialog the areas should also disappear in the map

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender:3.2.4
 - 
**Screenshots / Logmessage**
1. admin configuration
![Bildschirmfoto vom 2021-03-11 17-59-46](https://user-images.githubusercontent.com/996298/110825479-5fdcab00-8294-11eb-94f0-9b749570641d.png)

2. featureinfo - see highlighted area
![Bildschirmfoto vom 2021-03-11 18-02-16](https://user-images.githubusercontent.com/996298/110825503-6703b900-8294-11eb-897e-7c249412660c.png)

3. dialog closed - areas are still visible
![Bildschirmfoto vom 2021-03-11 18-02-22](https://user-images.githubusercontent.com/996298/110825520-6bc86d00-8294-11eb-985e-5d9e94ad4d5e.png)

**Comment by thzanger** [comment]
Dear @astroidex, I was apply to recreate your issue and forwarded it into our internal MB ticket system.

**Comment by rschwammborn** [comment]
Given the scenario, this is not a real bug but more of a workflow inconvenience.
There are two different solutions to make the highlighted areas disappear:

1. Deactivate FeatureInfo the same way it was activated before after closing the dialogue (involves an additional click) or
2. Activate the checkbox "Deactivate on close" in the backend settings (which comes with the minor inconvenience to activate FI afterwards if more requests are needed = sometimes an additional click).

Because of these already existing alternatives, I'm closing the issue.
