### ISSUE TITLE
WMTS Layer Does Not Allow Selection When Not Defaulted to On

### ISSUE THREAD

**Issue by lf73** [mapbender/mapbender#1415]
When using a WMTS layer in which you wish to have the layer not immediately displayed, the layer in the layertree is disabled and can not be toggled on. If the WMTS layer is defaulted to display, then the user can correctly turn the layer on and off.

**To Reproduce**
Create a WMTS Source
Under a map application, layersets, add the WMTS source
Modify the layerset and deselect "SELECT ON".
Save
View Map
Observe Layer in Layertree is listen, but disabled.

**Expected behavior**
The WMTS layer listed in the layertree should be able to be toggled on.

**Versions **
 - Mapbender: 3.2.9
 - Database: Demo SQLight DB
 - Browser: Chrome

**Additional context**
WMS layers work fine. Also WMS layer present a root selection, or hierarchy, with the actual layers nested. WMTS brings in all layers flat. Also notices if the are multiple layers in WMTS, it is not possible to select induvial layers as the "Folder" icon does not expand in the layertree like WMS sources.  

Perhaps this is because WMTS sources were meant to be a Basemap.  But seeing WMTS works perfectly otherwise, while initially toggled on, this flexibility would be greatly appreciated.

**Comment by rschwammborn** [comment]
Hello @lf73,

sorry for the rather late reply. Sadly, this bug is due to a known restriction when using WMTS layers in Mapbender - the functionality to handle other than one layer is not supported (yet). As of right now, it is impossible to deselect a WMTS layer by default, because the module always needs one layer to work. To see all restrictions of WMTS, check [the initial WMTS PR](https://github.com/mapbender/mapbender/pull/1116).

On the same note, we are still looking for funding concerning a better WMTS implementation in Mapbender.

Greetings!
