### ISSUE TITLE
What does this mean in dev log file? 

### ISSUE THREAD

**Issue by YourErik** [mapbender/mapbender#1479]
**Describe the bug**

**To Reproduce**
![Clipboard01](https://github.com/mapbender/mapbender/assets/18585429/a9b104df-1eef-4c1e-aeb5-19f3fca13114)

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: [e.g. 3.0.6.3]
 - Database: [e.g. PSQL 9.5.12]

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Additional context**

**Comment by Phocacius** [comment]
Hi @YourErik, thank you for your issue!

Unfortunately I cannot help you with the information provided. The logs shown in the screenshot only show deprecations, that is, methods that will be removed in a future version of symfony or symfony libraries. They will be approached during the next months when there will be the next major release that includes the update to Symfony 5. However, they are only notices that don't affect the application's behaviour.

Try the following:
- if possible, host your application on a local server, then use `app_dev.php` as an entry point to your installation instead of `app.php`. The debug functionality will be enabled and the error should be printed to you.
- Check other possible locations for error log files outside the mapbender directory. They depend on your webserver installation, e.g. for Apache you usually find them in `/var/log/apache2/err.log` if not configured otherwise in a virtual host. When using Symfony's built-in webserver, error messages should be printed right in the console window you started the webserver with.

Good luck!

**Comment by Phocacius** [comment]
I'll close this due to missing feedback. If the issue still remains, feel free to re-open and comment.
