### ISSUE TITLE
error when i click sources in admin dashboard

### ISSUE THREAD

**Issue by YourErik** [mapbender/mapbender#1520]
![Screenshot 2023-11-08 094334](https://github.com/mapbender/mapbender/assets/18585429/e3e38660-6a4a-4915-81aa-18193aa6dd99)
![Screenshot 2023-11-08 094459](https://github.com/mapbender/mapbender/assets/18585429/b6bb7815-84cb-404a-97b4-940d08e5cb96)

![Screenshot 2023-11-08 094629](https://github.com/mapbender/mapbender/assets/18585429/37d543f8-e51d-47e1-abcc-846af4463640)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: [e.g. 3.0.6.3]
 - Database: [e.g. PSQL 9.5.12]

**Screenshots / Logmessage**
If applicable, add screenshots or a logmessage from app/logs to help explain your problem.

**Additional context**

**Comment by rschwammborn** [comment]
Hello @YourErik ,
thanks for using Mapbender. Does this error still occur? To see what exactly is going on here, some insight on your system state while the error happened (e.g., Mapbender version) would be very helpful - this is why there's the issue template that you posted (but didn't fill out yet).

**Comment by YourErik** [comment]
yes still occur. Mapbender version 3.3.2

**Comment by Phocacius** [comment]
Hi @YourErik I'm afraid with the provided information, no help can be provided. 

Try clearing the cache (`app/console cache:clear`), try to enable development mode using app_dev.php (https://doc.mapbender.org/en/installation/installation_configuration.html?highlight=app_dev#production-and-development-environment-and-caching-app-php-and-app-dev-php) and provide more information if the issue still occurs and can't fixed by yourself using the error message you'll receive in development mode. Feel free to reopen if you have further information.
