### ISSUE TITLE
mb.wms.repository.parsed_not_valid_xsd

### ISSUE THREAD

**Issue by mauriciruiz** [mapbender/mapbender#1531]
Dear Mapbender users,
I am currently using MapBender to create a cartographic viewer that retrieves WMS (Web Map Service) from GeoServer. I have installed the most recent versions of these applications on an Ubuntu system. However, I'm encountering an issue: whenever I add new layers to GeoServer using QGIS and GeoCatBridge, MapBender generates an error: mb.wms.repository.parsed_not_valid_xsd. I am not sure why this is happening. I've tried restarting GeoServer, but the problem persists. Could anyone provide a solution or suggest what I might do next?

Thanks in advance
Kind regards
Maurici Ruiz

**Comment by astroidex** [comment]
Hello @mauriciruiz, great that you use Mapbender.

Please discuss your problem on the mailing list https://mapbender.org/en/mapbender-users/
I will close the issue here.

Some ideas
- please check the getCapabilities of GeoServer
- Is it a public WMS? If yes you could share the URL on the mailing list
- is https supported
