### ISSUE TITLE
[Bug] Mobile Template Layertree - scroll is not possible when sort layers is active 

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1617]
**Describe the bug**
Mobile Template: when "Allow Reorder" for layers is activated in the Layertree it is not possible to scroll. 

**To Reproduce**
1. Go to https://schulung.foss.academy/mapbender4a/application/mapbender_mobile_bug
2. "Allow Reorder" is activated: so you can move wms but you can not scroll to the bottom (on mobile devices)
3. When you deactivate "Allow Reorder" in the backend or can scroll again 

- see also mailing list conversation https://lists.osgeo.org/pipermail/mapbender_users/2024-August/006395.html

**Expected behavior**
it should always be possible to scroll

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 4.0.0
- Browser firefox

**Comment by Phocacius** [comment]
Additional context: Currently the whole width of the layer is a target for the jQuery  UI sortable widget. The options for resolving this issue are:

- restricting the area where reordering is possible. E.g. the touch area where reordering is possible might be restricted to the burger menu at the right side, or the margin on the left side could be used for scrolling while the rest allows reordering
- use two-finger gestures for scrolling while one-finger gestures still only are used for reordering. E.g. Google Maps uses this pattern. This must be communicated though since it's not intuitive.
