### ISSUE TITLE
Map onmouseOver feature 

### ISSUE THREAD

**Issue by marmancs** [mapbender/mapbender#313]
It would be nice to have a feature similar to 
Mod_usemap in Mapbender2,
where User got information OnmouseOver in the Map.
see:
http://www.mapbender.org/UseMap
We used it in Remscheid in a few applications:
See here for example.
http://geoportal.remscheid.de/mapbender/frames/login.php?name=baust&password=xbaust

**Comment by ruhri** [comment]
same idea... :+1:

**Comment by ruhri** [comment]
How about realizing this via UTF-Grid:
https://www.mapbox.com/help/an-open-platform/#scalable-interactions
also supported by Leaflet, OpenLayers (http://dev.openlayers.org/examples/utfgrid.html) and UMN-Mapserver (http://mapserver.org/development/rfc/ms-rfc-93.html) encapsulated in WMS-Requests.
IMHO this would be an "more standard" way and one could also use services from foreign sources - not just the own DB...

**Comment by AxxL** [comment]
Correct link from @marmancs after domain-change: https://www.mapbender2.org/UseMap

**Comment by werrolf** [comment]
We are generally not going to readd features that are described as "like in Mapbender2".
Mapbender2 had only a small fraction of the features current Mapbender has. Whenever you see something missing, it's because it would come into technical or conceptual conflict with something else.  

There are many ways in current Mapbender to show information about a feature. There's FeatureInfo, multiple flavours of search, Digitizer, DataManager, FeatureTypes, custom Wfs implementations, custom UtfGrid implementations etc.

My recommendation is always to implement bog-standard WMS GetFeatureInfo.  

This seems to be public brainstorming rather an issue that can be solved in any way, and all the links are dead, so I'm going to close this.   
Please refer to the mailing list for general idea exchange.
