### ISSUE TITLE
WFS searchs

### ISSUE THREAD

**Issue by federicogodan** [mapbender/mapbender#375]
Implement WFS searchs like 2.7 version, instead of solr

**Comment by AxxL** [comment]
We consider that and it will definitely come. There are some project solutions for WFS accesses but not general solution and we are going to change the data source api to prepare Mapbender for additional data sources. I cannot say right now when WFS is part of the release.

Solr is for high-performant and customizable searches on your local database.

**Comment by federicogodan** [comment]
was implemented?

**Comment by AxxL** [comment]
@federicogodan Right now it's not in our plan. But we are free to implement it on a project base. 

WFS is something that is paticularly important in SDI contexts, but it really needs some detailed requirements-analysis. The protocol isn't the problem but the workflow and what to ask and how to display the results and work with them.

On a project base means requirements-analysis, conception, estimation, financing and execution. 

I would like to have something like this in Mapbender but I don't have the ressources right now. We are working on some clarification of the technical stuff of Mapbender so that the community can participate on functions. Perhaps also on a WFS interface.
