### ISSUE TITLE
composer update/install tooni/fpdf

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#423]
If you want to do a composer update you'll notice an error concerning the package:  toooni/fpdf. The package cannot be found and used.

The package is referenced in composer.json:
        "toooni/fpdf": "dev-master",

We are looking for a solution how to prevent that issue and will provide a hotfix for that.

**Comment by eSlider** [comment]
Old "toooni/fpdf" package seams to be removed by the maintainer.
Anyway the original maintainer is "https://www.setasign.com/", so we migrate to "setasign/fpdi-fpdf" instead of "toooni/fpdf" library.

Fixed here: https://github.com/mapbender/mapbender/commit/da6150ec484667ba1175e1de84b4fdc073976180
Old "toooni/fpdf" package seams to be removed by the maintainer.
Anyway the original maintainer is "https://www.setasign.com/", so we migrate to "setasign/fpdi-fpdf" instead of "toooni/fpdf" library.

Fixed here: https://github.com/mapbender/mapbender/commit/da6150ec484667ba1175e1de84b4fdc073976180
