### ISSUE TITLE
bin/composer build How can I make a vendor package with the new build command

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#521]
Build -h lists several options

`bin/composer build -h`

I can create a build with
`bin/composer build tar.gz mbtest 3060 `

Question - how can I make a package with the vendor files?

**Comment by RobinSchwammborn** [comment]
@astroidex, vendor files will copied atomaticaly under `dist`. 

You can execute `dist` instead of `build` so you get only distributed files, and then manually create an archive of vendor files.  

More info how to build packages: https://github.com/mapbender/mapbender-starter/blob/fd85ef2078e6d9098c08cca26ce77f25f073ec9f/CONTRIBUTING.md#building-packages

**Comment by astroidex** [comment]
Thanks for the answer
