### ISSUE TITLE
Mapbender "Button" element is many things at once, configs mutually exclusive => split it up

### ISSUE THREAD

**Issue by werrolf** [mapbender/mapbender#571]
If it has "click" defined, it's a link. Values "target", "group", "activate", "deactivate" don't do anything. If click is defined but starts with a hash, it doesn't perform any function at all.
If it has empty "click" and empty "group", it toggles itself by calling activate and deactivate. If a "target" is defined, it calls "action" or the (literal) "defaultAction" method on that target.
If it has empty "click" and non-empty "group", it finds other elements with that group and triggers an mbButtonDeactivate event on them, which by default calls deactivate, thereby deactivating their "target"s, if defined.

Design seems to address three use cases:
1) Emulate a clickable link
2) Toggle active / inactive on a single "target" (e.g. FeatureInfo)
3) Encapsulate a group of "target"s of which only one can be active at any given time

I have not done enough archeology to actually see a full-fledged case of #3. I have only seen implementations of this use case with accordeons, not "Button" elements so far. I'm not sure this case is finished and deployed anywhere.

I suggest splitting the Button element into multiple elements each addressing only one use case and only containing configuration values relevant to that one use case.

**Comment by astroidex** [comment]
Hi,

I am fine with the way element button works at the moment. It is quite flexibel 

For me splitting up the button element is not a topic that is urgent or makes problems in my daily work. 

* easy to create a button to trigger an element and easy way to refer with a button to a link
* group is a nice way to toggle buttons. If a create a link maybe there is no need to define group. As is is not active - just opens the link
* "activate", "deactivate"  are not needed anymore as the action in handled in the background - we could hide this fields in the administration
* please if you split up the element you should keep in mind to provide an updateable solution

**Comment by AxxL** [comment]
@werrolf 
@swinkelmann had similar issues regarding utf-grid button which behaves like fetaureinfo button.

The group attribute seems to fulfill two different purposes:

a) Make a toggleable button with a state. Like FeatureInfo. Or Measure.
b) Put toggleable buttons together in a group where they have dependencies (see ##549)

Toggleable button: Problem is, the element can be set to "open at startup" so that it is active. The button doesn't know the state and is not activated.

Group: Problem is, not all buttons seems to honor the group, like POI. Also the feature is not documented.

Here is the plot-twist: Strategic solution is to get rid of this button - element combination and let them be placed by the element itself: The Toolbar-region is filled automatically by pushing the Elements into the content. You still have a button-element for your own joy or own function - whatever. But all MB-elements have their own button defined by themselves, that is placed into the toolbar automatically when the element is part of the template.

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
