### ISSUE TITLE
Redlining: Anchorpoint for texts is part of printout

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#574]
If you redline a text, the anchorpoint will be part of the PDF-print ("orange kuller").

**Comment by swinkelmann** [comment]
This bug was already fixed. 
See #493 
It has not  been merged yet. I dont know why.

**Comment by swinkelmann** [comment]
Fixed together with #573 
branch: hotfix/print-redline-size
Pull Request: #575

@AxxL please have a look.

**Comment by AxxL** [comment]
Fixed.

**Comment by AxxL** [comment]
Merged.

Waiting on Branch delete and update composer.json and composer.lock

**Comment by eSlider** [comment]
Composer dependence became upgedated
https://github.com/mapbender/mapbender-starter/commit/c3521f5f385ad31e60e04766cf3260d308413b08

**Comment by astroidex** [comment]
Reopen Ticket as it is not fixed in version 3.0.7.7

The red anchor point is still there in print. Tested with Version 3.0.7.7. https://demo.mapbender.org/application/mapbender_user  

![redlining_print](https://user-images.githubusercontent.com/996298/52196768-54b92480-285d-11e9-8471-f863f1c59144.png)

The anchor point in the application is new (it should help to move a text). But it should not show up in the print output

**Comment by werrolf** [comment]
Re-closing ticket.   
Print renders the point as seen.  
If you think the point should not be seen in the browser either, take the time to write that out as a sentence.
