### ISSUE TITLE
Display wrong WMS layer 

### ISSUE THREAD

**Issue by Poldy1705** [mapbender/mapbender#602]
Mapbender 3.0.6.3
PHP 7.1.8 NTS-VC14-x64
Postgres 9.6.4.1 64bit
Apache 2.4.23
Wincache 2.0.0.8-7.1 NTS-VC14-x64
Windows 2012 Server R2 Standard (;-)

I implemented a data source with about 10-15 Layers and displayed them with a Change Background Element.
Sometimes when i put new layers in my source-WMS or delete or rename i reload the source so the changes will take affect to my defined layersets.

This behavior affects sometimes directly the requested Layers by the Change Background Element.
![1kv_layerset_1](https://user-images.githubusercontent.com/29286915/29364534-15a31500-8294-11e7-87f7-83349863639c.PNG)

![1kv_layerset](https://user-images.githubusercontent.com/29286915/29364547-1ebfdb82-8294-11e7-96f1-5fc65f47e636.PNG)

![image](https://user-images.githubusercontent.com/29286915/29364602-51858756-8294-11e7-8607-b7fa9baae451.png)

**The Change Background Element: There is no other layer activated than 1 kV**
![image](https://user-images.githubusercontent.com/29286915/29364656-861926b2-8294-11e7-978b-575f75faaff9.png)

**The Sidepane:**
![image](https://user-images.githubusercontent.com/29286915/29364788-f20fb2be-8294-11e7-832c-7943d5c406f5.png)

This is one of the Requests that were generated by activating the Layer 1 kV. The request goes on the source MSP and not on NSP.

https://maps.stadtwerke-lemgo.de/mapproxy/service?_signature=0%3AhDYlpow95Vwcp9kOyf1uCZTEY5E&TRANSPARENT=FALSE&FORMAT=image%2Fpng&VERSION=1.1.1&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=WMS&REQUEST=GetMap&STYLES=&**LAYERS=MSP**&SRS=EPSG%3A25832&_OLSALT=0.47785564930311875&BBOX=493561.5964448,5764182.0024716,493633.27681392,5764253.6828408&WIDTH=512&HEIGHT=512

It's nowhere defined. In the Layerset of 1kV the MSP Source is definetly deactivated as you can see in the screenshots above. Also in the Instanceset for 1 kV in the Change Background Element there is nothing else activated nor 1 kV.

I think something went wrong witch the id's of the layers in the postgres database.
Even deleting the WMS Source and reconfiguring all doesn't solve the problem. Solely deleting the database in postgresql and recreate it brings the solution.

This behavior could be reproduced on a Windows 7 Notebook with the same software versions.

**Comment by AxxL** [comment]
@Poldy1705 Thanks for your report.

Trying to narrow it down and to reproduce. Can you check if this summary here is right?

* Put WMS in BaseSourceSwitcher (Change Background), maybe a complex one with many layers.
* Changing structure in WMS by adding/removing layers (somewhere in UMN or else)
* Reloading WMS in Mapbender (at Data Sources)
* Checking Layerset-Instance (the big dialogue with the many checkboxes)

Observed Behaviour:
* BaseSourceSwitcher calls wrong layers which are switched off in Layerset instance (here: MSP Mittelspannung layer)

Expected Behaviour:
* Only the NSP should be called (Niederspannung)

Can you check if you put the layersetinstance "5/45" into the TOC, if all layers are checked according to your configuration?

I'll try to reproduce that.

**Comment by Poldy1705** [comment]
@AxxL 
Your summary is exactly what i have done. 

What do you mean with "Can you check if you put the layersetinstance "5/45" into the TOC, if all layers are checked according to your configuration?"

The layersetinstance 5/45 is the only one checked in the Change Background Element: There is no other layer activated than 1 kV. In the instance itself there is also no other Layer activated.

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
