### ISSUE TITLE
[documentation] please write about bin/composer in git-install documentation or somewhere else

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#634]
now with Mapbender 3.0.6.x you can use bin/composer. Looks like documentation can be improved.

Information about the following would be great:
```
cd application
bin/composer -shows possibilities
bin/composer install
bin/composer update --no-devs
bin/composer update
bin/compsoer clean
```
Please write about the possibilities in the documentation and when to use which one.

https://github.com/mapbender/mapbender-starter/blob/release/3.0.6/CONTRIBUTING.md#installation

Maybe it makes sense to merge the pull request: https://github.com/mapbender/mapbender-starter/pull/49

If I just did not find the documentation and it already exists, let me know.

**Comment by AxxL** [comment]
@eSlider @werrolf Should be part of the developer documentation.

**Comment by LazerTiberius** [comment]
```
bin/composer -shows possibilities
```
There is no command like this. 

Except for the "clean"-command, all of these are basic composer commands. I disagree completely with the opinion to document these in the MB3-documentation.  Changes in these commands are not in our control.  Please use the official documentation for these commands https://getcomposer.org/doc/03-cli.md .otherwise there is a high risk that our information is outdated and wrong! Developers using this commands should be familiar with handling php-Projects using composer for dependency-management.

**Comment by astroidex** [comment]
* The link https://getcomposer.org/doc/03-cli.md shows 30 commands. Nice to have the list. But only some are important to handle Mapbender.
* so it would be great to have a list of the important commands and a link to official documentation

**Comment by AxxL** [comment]
We will provide a list of the important commands regarding Mapbender in Contribution.md. The documentation itself will be part of the API aka code. This is developer area.

> Lazer: I disagree completely with the opinion to document these in the MB3-documentation.

Sure.

**Comment by werrolf** [comment]
[Leading composer documentation](https://getcomposer.org/doc/).
