### ISSUE TITLE
[OL] [Implementierung] Ruler

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#683]
- [x] line mode
   - [x] draw
   - [x] live display of calculated length
- [ ] area mode
   - [x] draw
   - [x] live display of calculated area
   - [ ] correct calculation of non-convex shapes ("donuts"): currently calculated area keeps growing with every vertex, no matter where

**Comment by werrolf** [comment]
Error in widget deactivate method when activating (?) the widget (embedded in content) via button (embedded in top toolbar).
"Uncaught TypeError: Cannot read property 'model' of null"

```
deactivate:  function() {
            this.active = false;
            this.map.model.removeAllFeaturesFromLayer(this.id, this.layerId);   // <== here
            this.map.model.removeVectorLayer(this.id, this.layerId);
            $("#linerulerButton, #arearulerButton").parent().removeClass("toolBarItemActive");

        },
```
Assumption: map not initialized because activate() does that and hasn't been called yet.  
Assumption: might work when widget is placed in sidepane.

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
