### ISSUE TITLE
Some WMS cannot be added with wms-loader in frontend.

### ISSUE THREAD

**Issue by kartoffelfee** [mapbender/mapbender#706]
Some WMS cannot be added with wms-loader in frontend.
The WMS gets an entry in the layertree and legend, but is not visible in
the map.

The network inspector shows the GetCapbilities-Request and the
getLegend-Request, but no getMap-Request.

But the WMS can be added as datasource in the backend and then is
visible in the map.

examples:
(you should call it with the poi-function, because the WMS only covers a
very small property)
https://release.mapbender3.org/application/wmcredlining?poi%5Bpoint%5D=12.61664%2C52.38401&poi%5Bscale%5D=10000&poi%5Bsrs%5D=EPSG%3A4326&poi%5Blabel%5D=Please+take+a+look+at+this+POI%3A

here the wms:
http://www.geoportal-klosterlehnin.de/isk/lehn_bp53?SERVICE=WMS&REQUEST=GetCapabilities

there are some more WMS with this behavior in Mapbender, but this is the
only one with I know with free access.

**Comment by astroidex** [comment]
Hi @kartoffelfee

looks like with Mapbender handles the scale enominator different when you load a WMS via frontend.

WMS Loaded via WMS Loader: The layers are displayed lightgray in the layertree that means out of the visible scale -> therefore no maprequest is send.

In the getCapabilities it says:
for WMS 1.3.0: <MinScaleDenominator>490</MinScaleDenominator>
for WMS 1.1.1: <ScaleHint min="0.244462395730522" max="0"/>

-> both results to minscale: 1:490 and no maxscale limitation

In the WMS-Instance in the backend it says too: Minscale 490  -> which is ok

So for scale 1:1000 the service should be visible.

Now the question is, why the scales are handles different in the frontend and how.

**Comment by werrolf** [comment]
Because the WmsLoader reimplements caps parsing and transformation to config, even though we have a working server-side implementation, even though loading a WMS via WmsLoader already makes at least two ajax roundtrips to the server.
https://github.com/mapbender/mapbender/blob/e7ee068eb8c494683bb71fc39937f0766df710bf/src/Mapbender/WmsBundle/Resources/public/mapbender.geosource.wms.js#L108
https://github.com/mapbender/mapbender/blob/e7ee068eb8c494683bb71fc39937f0766df710bf/src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js#L208

We should not strive to "improve" this JS reimplementation until it behaves the same; we should let the server-side code do all of that work instead.

**Comment by DeEgge** [comment]
Trying to load the provided WMS http://www.geoportal-klosterlehnin.de/isk/lehn_bp53?SERVICE=WMS&REQUEST=GetCapabilities results in an XML validation error. The problem is, that you can't set whether you want to load only valid or non valid WMS, and by default, the WMS loader will only load valid ones. https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/WmsBundle/Component/Wms/Importer.php#L36

**Comment by DeEgge** [comment]
Quick fix:
Change `$onlyValid` to `false` on line https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/WmsBundle/Component/Wms/Importer.php#L36

On a larger scale... https://github.com/mapbender/mapbender/pull/781

**Comment by AxxL** [comment]
Fixed:
![auswahl_017](https://user-images.githubusercontent.com/2235393/37278048-c9f8e818-25e6-11e8-8f9b-cfc7a30357fe.png)

**Comment by DeEgge** [comment]
OnlyValid-checkbox needs to be removed!

**Comment by DeEgge** [comment]
OnlyValid-checkbox was removed with https://github.com/mapbender/mapbender/pull/820/commits/2b31b0aa7361c61c059e4708463c15150969c26c in https://github.com/mapbender/mapbender/pull/820
