### ISSUE TITLE
Remove obsolete debug mode

### ISSUE THREAD

**Issue by atd-schubert** [mapbender/mapbender#726]
There is a obsolete implementation of `isDebugMode` in [`mapbender.application.js`](https://github.com/mapbender/mapbender/blob/release/3.0.6/src/Mapbender/CoreBundle/Resources/public/mapbender.application.js#L95).

In addition there is a `Mapbender.initElement(id,data);` without error handling in `DubugMode` and with error handling when it is not in `DebugMode`.

In my opinion this structure makes no sense...

**Comment by eSlider** [comment]
@atd-schubert, is there some troubles or just an opinion? I use DebugMode by development.

**Comment by atd-schubert** [comment]
It is more or less just a question, if we still need this or if it just some kind of dead code.

**Comment by LazerTiberius** [comment]
Debug mode shoudn´t be necessary with a proper error handling. But  this error handling does not do well. e.G. 


```
console.error('Your element with id ' + id + ' (widget ' + data.init + ') failed to initialize properly.');
```
This line does not give any information you need as a dev and is  only relevant for the admin of the app, maybe change it to a notice.


```
console.log('Error:', e);
```
Just change is to ` console.error(e);`
```
if(Error) {
 console.log(Error().stack);
            }
```
Unless you overwrite it with a falsy value the constructor of the global Error object will be always `true`. And creating a new Error-Object and accesing the stack propertie will give you stack trace to this line of code but with no relevant information to the real error `e`.  This should be legacy code for old IE-Versions and is not relevant anylonger.


Because the mapbender way to init a widget is kind of a polution for the `error stack trace`, we should consider to raise the size of the `error stack trace`. Adding `Error.stackTraceLimit  = 30` (or a similiar high value) should help debugging errors in the widget initialization and make debug mode obsolete
