### ISSUE TITLE
[Backend][Element] add help Button to every element and link to documentation

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#786]
* to make access to the documentation easier it would be great to have a link in each element to the documentation of the element
* we would have to decide whether to link to the online documentation f.e. https://doc.mapbender3.org/en/bundles/Mapbender/CoreBundle/elements/button.html or to the internal documentation that was published with the release 

f.e.
![mb2](https://user-images.githubusercontent.com/996298/37212655-ee787d36-23af-11e8-8f25-1cbc528b4d06.png)

**Comment by AxxL** [comment]
Good idea.

- If it's linked to the internal documentation, all our projects must be shipped with this and every build has to be adjusted to that, otherwise dead-link. That's right now not the case.

- If it's online, you either have the link to the most current documentation although your version might not be current. Or to a fixed version.

- Changes in the structure of the documentation have to be adjusted to the elements.

**Comment by eschuettler** [comment]
In order to get a better overview we will clean up old issues.
If the issue requires further attention, feel free to open a new issue.
Thank you!
