### ISSUE TITLE
Developer Guide - update or remove CONTRIBUTING.md

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#803]
There are some missing or wrong parameter and abstracts in the developer guide (CONTRIBUTING.md in mapbender-starter ): 
* https://github.com/mapbender/mapbender-starter/blob/release/3.0.6/CONTRIBUTING.md

previously noticed points: 
* missing package php-bz2 (https://github.com/mapbender/mapbender-starter/blob/release/3.0.6/CONTRIBUTING.md#preparing-system) 
* you need to define the root user and configure some parameters from the normal documentation (https://github.com/mapbender/mapbender-starter/blob/release/3.0.6/CONTRIBUTING.md#start-web-server)

Maybe you can integrate some things from this developer guide into the normal documentation or the other way - from the normal doumentation in the developer guide... in the current form, it is easy to double data retention and create outdated versions of the same documentation.

**Comment by AxxL** [comment]
AFAIK bz2 is only needed for developing. So Contributing-Guide is appropriate. 

Good point for root user.

Doubling: User-Guide is for installing on a user system. With the ZIP. The GIT-Guide could be adjusted but only for using, not developing. So `composer install` instead of `update` and no debugging commands.
