### ISSUE TITLE
WMS loader loads no WMS

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#818]
Regression error with any WMS loaded in WMS Loader.

**Comment by werrolf** [comment]
Error traced to directory-relative xsd reference in upstream schema.
[See inspire common.xsd](http://inspire.ec.europa.eu/schemas/common/1.0/common.xsd) near the top.
```
<xs:include schemaLocation="network.xsd"/>
```

Working on a fix ...

**Comment by werrolf** [comment]
Collateral:
The addition of the "onlyValid" param to the WMS Loader interface is faulty, because the request parameter is [transmitted as "onlyValid"](https://github.com/mapbender/mapbender/blob/4882e1c05c703564ea4aeab0d854bc2a116affd7/src/Mapbender/WmsBundle/Resources/public/mapbender.element.wmsloader.js#L180), but [looked up as "onlyvalid"](https://github.com/mapbender/mapbender/blob/4882e1c05c703564ea4aeab0d854bc2a116affd7/src/Mapbender/WmsBundle/Element/WmsLoader.php#L197). This makes the value used server side is always null.

**Comment by werrolf** [comment]
Basic function restored, DTD / XSD validation is now skipped entirely by WmsLoader.

Relative XSD references are now purely a backend loading issue.
