### ISSUE TITLE
Missing Print Error when Service not available at frontend

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#853]
Steps to reproduce:

- Build an application containing a service that isn't available anymore.
- Print.
- Message: 500

Expected:

- The extra tab closes. I don't mind that thing.

- I get a print download, even if one service couldn't give an image.

- Error message at the frontend (not the extra tab. flash error message at the top-right): Cannot print because WMS-Error: And print the error you've recieved from the WMS. (depends on error handling): "Error on printing: WMS <name of WMS> didn't return an image."

**Comment by inacht** [comment]
The print pdf request is made via xhttp instead of via form submitting now (refactoring). A new tab is not opened anymore. Invalid layer urls and internal server side errors do not hinder the generation of the pdf document.

PR https://github.com/mapbender/mapbender/pull/987

Branch: fix/print-with-invalid-sources

For testing you can go to application/mapbender  and checkout the named Branch
