### ISSUE TITLE
Print client - Representation of special characters in the text and 

### ISSUE THREAD

**Issue by CharlyUnicorn** [mapbender/mapbender#859]
If you insert text with special characters like " – " the print displays it with a "?"..this is not really bad, but maybe more characters could be supported here.

Test with the text from the sponsoring site: 

`Unser Ziel ist es, an den Funktionalitäten der einzelnen Mapbender-Elemente nichts zu ändern. Selbstverständlich erfolgen – wenn nötig – Korrekturen und ....`

![auswahl_030](https://user-images.githubusercontent.com/13517141/41414901-89bf30ea-6fe7-11e8-9ddd-e187eaf031d2.png)

Furthermore the line spacing is not editable in one way: make line spacing bigger is possible (more textlines in the element in the template), but to make it smaller i found no solution.

**Comment by astroidex** [comment]
Hi Charly. This issue is fixed already.
* see ticket: https://github.com/mapbender/mapbender/issues/690
* see PullRequest: https://github.com/mapbender/mapbender/pull/691
* https://github.com/mapbender/mapbender/blob/master/src/Mapbender/PrintBundle/Component/PrintService.php#L388

So with update to 3.0.7.0 it will be fixed
