### ISSUE TITLE
[OL] [Implementierung] Redlining

### ISSUE THREAD

**Issue by AxxL** [mapbender/mapbender#908]
- [ ] Draw geometries
  - [x] Point
  - [x] Line
  - [x] Polygon
  - [x] Rectangle
  - [x] Text
  - [ ] Circle 😍
- [x] Remove geometries
- [x] Zoom to geometries
- [x] Edit geometries

**Comment by DeEgge** [comment]
https://github.com/mapbender/mapbender/commit/025c93f4f04ded46add83c246f92a8231ca7e781

**Comment by DeEgge** [comment]
https://github.com/mapbender/mapbender/commit/529a18dbcc57a7b61dc18f6234f77ad80c396ced

**Comment by DeEgge** [comment]
https://github.com/mapbender/mapbender/commit/ff48fbbf4afc8a98f204373df4bdca91aaff5670

**Comment by werrolf** [comment]
There seems to be a regression collateral to recent style handling changes.   
Vector features do not show on map anymore (temp drawing geometry is visible, finished geometry is not).  
Texts work fine though (including the little red point, not just the label).  

Redlining geometries also make the image export run into errors, which previously worked fine. Apparently the structure of the extracted style objects has changed significantly.   

We will probably require another session of defining our common internal format for vector styles.

Please check if there is any other potential reason (except style format) that geometries are not visible.

**Comment by inacht** [comment]
@werrolf the error could be reproduced. Line 437 in the model causes the problem (branch: ol4):
options.style = options.style ? this.createVectorLayerStyle(options.style) : this.createVectorLayerStyle();

options.style gets assigned an empty ol.style.Style object. The above code has been just recently added, and cause also that for the redlining the geometry disappears after having completed the drawing.

During testing i removed that line, and the problem was solved for redlining and the imageExport.
However, i don't know what the best solution is here, and so did not commit this.

Instead, i did adjust the getVectorLayerPrintStyleOptions Funktion that is used for the imageExport:
empty style objects of a vector layer  (empty fill, stroke and text objects) are handled by having default
vectorLayerPrintStyleOptions.





For the imageExport i did ensure that this

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
