### ISSUE TITLE
Mapbender.Util.Url not working under Openlayers 4

### ISSUE THREAD

**Issue by werrolf** [mapbender/mapbender#933]
... because [it builds on top of Openlayers.Util](https://github.com/mapbender/mapbender/blob/64003ad6891c6664efb7e80172444ac7e67ef183/src/Mapbender/CoreBundle/Resources/public/mapbender.application.js#L179).

Need an engine-independent solution. Either a different implementation for ol4 vs ol2, or our own implementation.

**Comment by inacht** [comment]
new Funktion defined and used for getting the parameters of an url (instead of using OpenLayers.Util.getParameters). I have found this under https://www.kevinleary.net/javascript-get-url-parameters/ (section Best Approach as of 2017) and changed it a bit.

Tested it with the this link https://demo.mapbender3.org/application/mapbender_user_yml/instance/35/tunnel?TRANSPARENT=TRUE&FORMAT=image%2Fpng&VERSION=1.1.1&EXCEPTIONS=application%2Fvnd.ogc.se_xml&SERVICE=WMS&REQUEST=GetMap&STYLES=,,&LAYERS=osm,osm_ch,osm_at&_OLSALT=0.35613212050479137&SRS=EPSG%3A25832&BBOX=370916.48487153,5622326.5519728,372708.49409966,5624118.5612009&WIDTH=256&HEIGHT=256,

it worked fine.

**Comment by werrolf** [comment]
Works well.  
Merged into ol4.  
Closing.
